baseURL = "https://schickmalzwo.de/"
languageCode = "en-us"
title = "schickmalzwo"
theme = "landing-page"

[[params.social]]
	title = "soundcloud"
	icon = "soundcloud"
	url = "https://soundcloud.com/schickmalzwo"
[[params.social]]
	title = "facebook"
	icon = "facebook"
	url = "https://facebook.com/schickmalzwo"
[[params.social]]
	title = "youtube"
	icon = "youtube"
	url = "https://www.youtube.com/channel/UC11PIQFw33nU7bvddl_ZTYw"
[[params.social]]
	title = "email"
	icon = "envelope-o"
	url = "mailto:verschickt@schickmalzwo.de"